# Generated by Django 3.2.9 on 2021-11-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('summary', models.TextField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('image_url', models.TextField()),
            ],
        ),
    ]
